services:
  api:
    image: sherensberk/hisoka_api:latest
    build: .
    ports:
      - 80:8000
    env_file:
      - .env.prod
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ./entrypoint.sh
    networks:
      - network
  postgres:
    image: postgres:15
    env_file: .env.prod
    volumes:
        - db_volume:/var/lib/postgresql/data
    ports:
        - 5432:5432
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  db_volume:
      driver: local
networks:
    network:
        driver: bridge